twitter:
  consumer_key: PVJbmB6Xfv7FvQl3ch50X5puO
  consumer_secret: eDb2W2luBoqM2Z1DiK4jMNexUd0NhDkODkNn5mCHdkz3Jrqt9N
  bot:
    access_token_key: 887120467835756544-Tf1ZsejqDnm7Zym25WYz665981N7BeH
    access_token_secret: gq5gSDV8lmUkiNKX4FmBPkszgMCqAA7ksH769vMH2Gb0c

google_api:
  key: AIzaSyClMI20_tDalmPvWasKC7Z5gxheBNKwMJE