default: &default
  adapter: mysql2
  pool: 5
  timeout: 3000
  host: <%= ENV.fetch('MYSQL_HOST', 'localhost') %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4

development:
  <<: *default
  database: board_game_mania_development

test:
  <<: *default
  database: board_game_mania_test

production:
  <<: *default
  database: board_game_mania_production