(function(g){var window=this;var axa=function(a,b){var c=new g.QI;c.o=a.o;c.D=a.D;c.C=a.C;c.B=a.B;c.G=a.G;c.F=a.F;c.I=a.I;c.g=b;return c},a6=function(a){return a.g?a.g.languageCode:a.o},b6=function(a){var b={format:a.A,
languageCode:a.o,languageName:a.D,displayName:g.RI(a),kind:a.B,name:a.C,id:a.ya,is_servable:a.N,is_translateable:a.G,vss_id:a.F};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},c6=function(a){if(!bxa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(cxa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},dxa=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;
for(c in b)if(!(c in a))return!1;return!0},exa=function(a){for(var b in a)delete a[b]},d6=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.aS.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.C=f;this.o=k},e6=function(a,b,c,d,e){g.aS.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},g6=function(a){a=void 0===a?{}:a;
var b="_"+f6++;return new e6(0,0x8000000000000,0,b,a)},j6=function(a,b,c,d,e,f){var k={};
g.Ha(k,b);g.Ha(k,a.params);g.Ha(k,c);var l={};g.Ha(l,b.rb);a.params.rb&&g.Ha(l,a.params.rb);g.Ha(l,c.rb);k.rb=l;g.Y.call(this,{H:"div",M:"caption-window",R:{id:"caption-window-"+a.id,dir:k.ck==h6.iq?"rtl":"ltr",tabindex:0,"aria-live":"assertive",lang:k.lang},K:[{H:"span",M:"captions-text"}]});this.B=[];this.J=!1;this.F=a;this.D=[];this.G=[];this.sa=e;this.ra=f;this.C=null;this.V=.96*e;this.ga=.96*f;this.o=k;this.pa=c;this.A=this.wa["captions-text"];this.ha=null!=this.A.style["box-decoration-break"]||
null!=this.A.style["-webkit-box-decoration-break"];this.L=d/360*16;this.type=i6.fq;this.aa=this.L*fxa(l);a=new g.uG(this.element,!0);g.L(this,a);a.subscribe("dragstart",this.aN,this);a.subscribe("dragmove",this.ZM,this);a.subscribe("dragend",this.YM,this);this.da=this.ea=0;a="";this.o.jk&&(a=c6(this.o.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.jk+")");b={"background-color":a,display:!1===this.o.isVisible?"none":"","text-align":gxa[this.o.textAlign]};this.ha&&(b["border-radius"]=a?this.aa/
8+"px":"");g.nh(this.element,b);switch(this.o.Tg){case 0:case 1:case 2:g.S(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.S(this.element,"ytp-caption-window-bottom")}},fxa=function(a){var b=1+.25*(a.gj||0);
if(a.offset==k6.gw||a.offset==k6.jw)b*=.8;return b},l6=function(a,b){var c={},d=b.background?b.background:a.o.rb.background;
if(null!=b.Ue||b.background){var e=null!=b.Ue?b.Ue:a.o.rb.Ue;d=c6(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ha&&(c["box-decoration-break"]="clone",c["border-radius"]=a.aa/8+"px")}if(null!=b.gj||null!=b.offset)c["font-size"]=a.L*fxa(b)+"px";d=1;e=b.color||a.o.rb.color;if(b.color||null!=b.Ih)e=c6(e),d=null==b.Ih?a.o.rb.Ih:b.Ih,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.Yh;f==g.M2.NONE&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+
d+")";b.Ww&&(k=e=b.Ww);var l=a.L/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case g.M2.DROP_SHADOW:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case g.M2.RAISED:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case g.M2.DEPRESSED:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case g.M2.qw:for(q=0;5>q;q++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case g.O2.Mv:e=
'"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case g.O2.Sv:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case g.O2.Lv:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case g.O2.CASUAL:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case g.O2.CURSIVE:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case g.O2.lq:e=g.lF()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case g.O2.lm:case g.O2.gq:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.rb.offset);switch(e){case k6.gw:c["vertical-align"]="sub";break;case k6.jw:c["vertical-align"]="super"}b.fontFamily==g.O2.lq&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Hs&&(c["font-style"]="italic");b.underline&&
(c["text-decoration"]="underline");b.Sr&&(c.visibility="hidden");return c},hxa=function(a,b,c){a.J=a.J||!!c;
var d={};g.Ha(d,a.o.rb);g.Ha(d,c||b.o);g.Ha(d,a.pa.rb);c=a.D[0];if(c&&d.background==c.background&&d.Ue==c.Ue&&!!d.Sr==!!c.Sr&&d.Yh==c.Yh){var e;for(e=0;e<a.D.length;e++)if(dxa(d,a.D[e])){var f=a.G[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Bd("SPAN");g.nh(f,l6(a,e));a.G[0].appendChild(f);e=1}a.G.length=e;a.D.length=e}else a.G.length=0,a.D.length=0,f=g.Bd("SPAN"),g.nh(f,l6(a,d)),a.A.appendChild(f);a.C&&a.C.parentNode!=f&&(g.Id(a.C),f.appendChild(a.C));c=(k=g.u(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.B.length||!b.C){if(0<e||0!=a.B.length){var m=g.Bd("BR");f.appendChild(m)}f.appendChild(g.Cd("\u00a0"));a.C=g.Cd("\u00a0");f.appendChild(a.C)}l&&(m=a.C,m.parentNode&&m.parentNode.insertBefore(k?g.Cd(l):l,m))}a.D.push(d);a.G.push(f);a.B.push(b)},ixa=function(){},n6=function(a){this.F=a;
this.B=this.o=this.mode=this.A=0;this.C=new m6(this);this.D=new m6(this);this.g=[];this.clear()},kxa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Tm:a,
Um:b,result:0};a=jxa[a];b=jxa[b];if(a&128){if(!(b&128)&&0!=c.g&&c.o==b)return{Tm:a,Um:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Tm:a,Um:b,result:2};return{Tm:a,Um:b,result:3}},mxa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.B&&a.reset(),a.C.g.clear(),a.D.g.clear()):(a.B=0,lxa(a.C,b,c,d))},nxa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.o=d.time;0==d.type?mxa(a,d.Rw,d.Sw,b):1==d.type&&a.A&496&&lxa(a.D,d.Rw,d.Sw,b)}a.g.length=0},o6=function(){this.g=0},p6=function(){this.o=this.A=this.g=0},q6=function(){this.timestamp=this.qe=0;
this.g=!1},r6=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new q6}this.g=this.o=this.Hc=0;this.style=new o6;this.C=a;this.B=0},s6=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.C.o+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!=r.qe){0==c&&(c=m,d=q);n=String.fromCharCode(r.qe);var w=r.timestamp;w<e&&(e=w);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.qe||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.o+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],r=q.qe,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),w=q.timestamp,w<=e&&(e=w),l+=n,q.reset()),32==m||0==r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},sxa=function(a,b){switch(a){case 0:return oxa[(b&127)-32];
case 1:return pxa[b&15];case 2:return qxa[b&31];case 3:return rxa[b&31]}return 0},t6=function(a){return a.A[a.Hc][a.o]},u6=function(a,b,c){2<=b&&1<a.o&&(--a.o,t6(a).qe=0);
var d=t6(a);d.timestamp=a.C.o+0;d.qe=sxa(b,c);32>a.o&&a.o++},txa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].pn(a.A[c+e][f])},v6=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},w6=function(a){a.Hc=0<a.g?a.g:1;
a.o=1;v6(a,0,15)},x6=function(a){this.B=a;
this.C=0;this.style=new o6;this.D=new r6(a);this.F=new r6(a);this.G=new r6(a);this.o=this.D;this.A=this.F;this.g=this.o},y6=function(a,b,c){var d=a.o,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:s6(d,c),w6(a.o),w6(a.A),d.Hc=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.B.mode=1<<d.B;e?d.o=1:d.g!=b&&(d.g>b?(s6(d,c),v6(d,d.Hc-d.g,b)):d.Hc<b&&(b=d.g),d.g=b)},uxa=function(a){a.style.set(1);
a.g=a.A;a.g.g=0;a.g.style=a.style;a.B.mode=1<<a.g.B},vxa=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.B.mode=1<<a.g.B},m6=function(a){this.o=a;
this.g=new p6;this.C=0;this.A=new x6(a);this.D=new x6(a);this.B=this.A},lxa=function(a,b,c,d){a.g.update();
b=kxa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Tm;c=b.Um;if(32<=e||!e)a.o.mode&a.o.A&&(b=e,b&128&&(b=127),c&128&&(c=127),e=a.B.g,b&96&&u6(e,0,b),c&96&&u6(e,0,c),!a.o.F&&0!=b&&0!=c&&3==e.style.g&&s6(e,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.A=e,b.o=c,b.g=2,b=e&8?a.D:a.A,a.B=b,a.o.mode=1<<(a.C<<2)+(b.C<<1)+(4==b.style.g?1:0),(a.o.mode|1<<(a.C<<2)+(b.C<<1)+(4!=b.style.g?1:0))&a.o.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&
14)>>1):0;c=b.g;switch(b.style.get()){case 4:d=c.Hc;break;case 3:if(d!=c.Hc){if(d<c.g&&(d=c.g,d==c.Hc))break;var f=1+c.Hc-c.g,k=1+d-c.g;txa(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));v6(c,b,e)}}c.Hc=d;c.o=a+1}else switch(e&7){case 1:switch(c&112){case 32:u6(b.g,0,32);break a;case 48:57==c?(b=b.g,t6(b).qe=0,32>b.o&&b.o++):u6(b.g,1,c&15)}break;case 2:c&32&&u6(b.g,2,c&31);break;case 3:c&32&&u6(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:uxa(b);break;
case 33:b=b.g;1<b.o&&(--b.o,t6(b).qe=0);break;case 36:b=b.g;d=t6(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.A[a][c]==d){for(;32>=c;c++)b.A[a][c].reset();break}break;case 37:y6(b,2,d);break;case 38:y6(b,3,d);break;case 39:y6(b,4,d);break;case 40:u6(b.g,0,32);break;case 41:b.style.set(2);b.g=b.o;b.g.g=0;b.g.style=b.style;b.B.mode=1<<b.g.B;break;case 42:d=b.G;d.g=15;d.style.set(4);w6(d);vxa(b);break;case 43:vxa(b);break;case 44:a=b.o;switch(b.style.get()){case 1:case 2:case 3:s6(a,d)}v6(a,0,15);break;
case 45:b:{a=b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.Hc){++a.Hc;a.o=1;break b}case 3:}2>a.g&&(a.g=2,a.Hc<a.g&&(a.Hc=a.g));b=a.Hc-a.g+1;s6(a,d);txa(a,b,b+1,a.g-1);v6(a,a.Hc,1)}break;case 46:v6(b.A,0,15);break;case 47:s6(b.o,d);d=b.A;a=b.B.o+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.A[c][e].timestamp=a;d=b.A;b.A=b.o;b.o=d;uxa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.o+=c&3)&&(b.o=32)}}},z6=function(){},A6=function(a){this.A=a;
this.o=null},xxa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?B6.qq:B6.Bm;a=g.vr("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");wxa(d,e,k,b,f,a.firstChild,{},c)},wxa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.Hs=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");C6.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new d6(a,b,c,d,n.nodeValue,e||0<m,g.Zb(k)?void 0:k));else{var q={};g.Ha(q,k);wxa(a,b,c,d,e||0<m,n,q,l)}}},D6=function(){this.A={};
this.o=null},E6=function(a){this.o={};
this.C={};this.D={};this.A="_"+f6++;this.B=a},F6=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},G6=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},H6=function(a,b){var c=F6(a,b);
if(void 0!=c)return c},I6=function(a,b){var c=a.getAttribute(b);
if(null!=c)return C6.test(c),c},yxa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ha(c,d?a.D[d]:a.B);d=H6(b,"mh");null!=d&&(c.Vs=d);d=H6(b,"ju");null!=d&&(c.textAlign=d);d=H6(b,"pd");null!=d&&(c.ck=d);d=I6(b,"wfc");null!=d&&(c.windowColor=d);d=F6(b,"wfo");void 0!=d&&(c.jk=d/255);return c},zxa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ha(c,a.C[d]);d=H6(b,"ap");null!=d&&(c.Tg=d);d=F6(b,"cc");null!=d&&(c.TH=d);d=F6(b,"ah");null!=d&&(c.ti=d);d=F6(b,"rc");null!=d&&(c.cp=d);d=F6(b,"av");null!=d&&(c.Oi=d);return c},Axa=function(a,b,c){var d={};
g.Ha(d,zxa(a,b));g.Ha(d,yxa(a,b));c?dxa(d,a.B)?(c=a.A,d=a.B):c="_"+f6++:c=b.getAttribute("id")||"0";a=F6(b,"t");b=F6(b,"d")||0x8000000000000;return new e6(a,b,0,c,d)},J6=function(a,b,c){this.F=c;
this.version=this.C=this.D=this.g=0;this.o=new window.DataView(a);this.A=[]},K6=function(a){var b=a.g;
a.g+=1;return a.o.getUint8(b)},Bxa=function(a){var b=a.g;
a.g+=4;return a.o.getUint32(b)},L6=function(a,b){this.B=a;
this.o="CC3"==b.D?4:0;this.A=new n6(!1);this.A.A=1<<this.o},Cxa=function(a){if(!(a.g<a.o.byteLength))return!1;
var b=Bxa(a);b.toString(16);if(1380139777!=b)return!1;a.version=K6(a);if(1<a.version)return!1;K6(a);K6(a);K6(a);return!0},Dxa=function(){this.o=[];
this.g=[]},M6=function(a,b){return b?a.g.concat(a.o):a.g},N6=function(a,b){switch(b.B){case "asr":var c=a.o;
g.fb(c,(0,g.A)(b.J,b))||c.push(b);break;default:c=a.g,g.fb(c,(0,g.A)(b.J,b))||c.push(b)}},O6=function(){this.o=null},Exa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Hs=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new d6(b,c,d,e.id,q.nodeValue,f||0<n,g.Zb(l)?void 0:l),m.push(q),e!=a.o&&e.o.push(q);else{var r={};g.Ha(r,l);Exa(a,b,c,d,e,!0,q,r,m)}}},P6=function(a){var b=0;
a=g.ma(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+c.value;return 1E3*b},Q6=function(a){g.K.call(this);
this.lz=!!a;this.o=new Dxa;this.C=[];this.g=null},Gxa=function(a){var b={};
if(a=a6(a))b.lang=a,Fxa.test(a)&&(b.ck=h6.iq);return b},Hxa=function(a,b,c,d,e){d=d||0;
e=e||0;if(g.u(b)){if("WEBVTT"==b.substring(0,6))return a.g||(a.g=new O6),a.g.g(b,d);b=g.vr(b);if(!b||!b.firstChild)return[];a.g||("timedtext"==b.firstChild.tagName?3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.g=new E6(Gxa(c)):a.g=new D6:a.g=new A6(Gxa(c)));return a.g.g(b,d)}try{if(g.u(b))var f=!1;else{var k=new J6(b,0,0);f=Cxa(k)}if(f)return a.g||(a.g=new L6(e,c)),a.g.g(b,d)}catch(l){g.OE(l)}return[]},R6=function(a){Q6.call(this,a.an);
this.B=void 0;this.A=null;this.C=a.captionTranslationLanguages},S6=function(){this.qb=[]},T6=function(a,b,c,d,e,f){g.K.call(this);
this.J=b;this.B=new S6;this.g=null;this.D=d;this.I=f;this.o=this.A=null;this.L=c;this.C=e||!1;this.F=new g.Et(this.Cz,1E3,this);g.L(this,this.F);this.G=new g.pG(this);g.L(this,this.G);this.G.P(b,"seekto",this.zA);this.zA(b.getCurrentTime());this.Cz()},U6=function(a,b){Q6.call(this);
this.D=a;this.T=b;this.A=null;this.B=!1},V6=function(a,b,c,d,e,f){j6.call(this,a,b,c,d,e,f);
this.type=i6.bq},W6=function(a,b,c,d,e,f){j6.call(this,a,b,c,d,e,f);
g.S(this.element,"ytp-caption-window-rollup");this.type=i6.hq;this.I=this.N=0;this.O=window.NaN;this.na=null;this.Y=new g.Et(this.GR,433,this);g.L(this,this.Y)},X6=function(a){if(!a.N){var b=g.Bd("SPAN");
g.nh(b,l6(a,a.o.rb));a.A.appendChild(b);b.appendChild(g.Cd("M"));var c=b.offsetHeight,d=g.Bd("BR");b.appendChild(d);b.appendChild(g.Cd("M"));a.N=b.offsetHeight-c;a.A.removeChild(b)}return a.N},Y6=function(a,b,c,d){Q6.call(this,d);
c=c||g.bF(a).hl||"";c=c.split("_").join("-");this.D=g.dF(a,{hl:c});this.B=b;this.F={};this.A=null},b7=function(a){g.aX.call(this,a);
g.nE();this.F=g.X(a);this.o=a.fa();this.ha=g.fW(a);this.T=a;var b=null,c=g.QD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.xD(c));this.ba=b;this.C={rb:{}};this.G={rb:{}};this.J=[];this.L={};this.V={};this.O=!1;this.na="1"==this.o.Xb.cc_auto_caps||"1"==this.F.N.cc_auto_caps;c=b=this.A=this.B=this.D=this.I=this.N=this.ga=null;Z6(this)||(b=new g.Bt(this.DD,void 0,this),g.L(this,b),c=new g.Et(this.qT,2E3,this),g.L(this,c));this.aa=b;this.da=c;this.Y=new g.pG(this);g.L(this,this.Y);Z6(this)||
this.Y.P(a,"resize",this.Gu);this.Y.P(a,"onPlaybackAudioChange",this.UO);this.Y.P(a,"crn_captions",this.GM,this);this.Y.P(a,"crx_captions",this.HM,this);$6(this,a7(this,"display-settings")||{})},Z6=function(a){if("3"!=a.F.B)return!1;
a=a.T.app.D;return!(!a||!a.g.textTracks)},Ixa=function(a){if(a.o.captionTracks.length)var b=a.g.uh().Ow;
if("FORCED_ON"==b||1==a.F.Xg||1==a.o.Xg||"alwayson"==g.sQ(a.o,"yt:cc"))return!0;if(2==a.F.Xg){var c=a7(a,"module-enabled");if(null!=c)return!!c}return"ON"==b||"on"==g.sQ(a.o,"yt:cc")},Jxa=function(a,b){if(a.B){var c=M6(a.B.o,b||a.na);
if(a.D&&a.D.g)return a.D.g;if(!a.F.experiments.g("legacy_default_caption_track"))for(var d=[a.o.Wg,a.F.Wg,g.sQ(a.o,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(a6(c[f])==d[e])return c[f];return a.D&&a.D.ar?a.D.ar:c[0]||a.D&&a.D.Ik}return null},c7=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c);a.A=b;a.load(d)},Kxa=function(a,b){var c=g.QZ(a.ha,!0).height;
if(!c)return null;var d=a.ha.Xa();switch(null!=b.params.Vs?b.params.Vs:b.params.aU?i6.hq:1<b.o.length?i6.bq:i6.fq){case i6.bq:return new V6(b,a.C,a.G,c,d.width,d.height);case i6.hq:return new W6(b,a.C,a.G,c,d.width,d.height);default:return new j6(b,a.C,a.G,c,d.width,d.height)}},$6=function(a,b,c){var d=d7.rb;
a.C={};g.Ha(a.C,d7);a.C.rb={};g.Ha(a.C.rb,d);a.G={rb:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;C6.test(f);e.rb.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;C6.test(f);e.rb.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||d7.windowColor;C6.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.Ue);e.rb.Ue=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;null==f&&(f=d.gj);e.rb.gj=f;e=b.textOpacityOverride?
a.G:a.C;f=b.textOpacity;null==f&&(f=d.Ih);e.rb.Ih=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=d7.jk);e.jk=f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.Yh);e.rb.Yh=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.rb.fontFamily=f;a.loaded&&a.Gu();c&&e7(a,"display-settings",b)},Mxa=function(a,b){if(b&&!a.I){var c=g6({ck:h6.Zp,
lang:"ja"});a.I=[c,new d6(c.start,c.end-c.start,0,c.id,g.U("YTP_SAMPLE_SUBTITLES"))];g.rW(a.g,a.I)}else!b&&a.I&&(Lxa(a,a.I),a.I=null)},Lxa=function(a,b){g.tW(a.g,b);
(0,g.H)(b,function(a){g.rb(this.J,a)},a);
a.aa.Sk()},Nxa=function(a,b){return a&&g.u(a)&&C6.test(a)?a:b},Oxa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},Qxa=function(a,b){if(a&&g.u(a)){var c=Pxa.indexOf(a);
return-1!=c?c:b}return b},Sxa=function(a,b){if(a&&g.u(a)){var c=Rxa.indexOf(a);
return-1!=c?c:b}return b},Txa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.Zc(a,-2,4):b},a7=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},e7=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.TJ.prototype.Qn=g.ca(2,function(a){return(a=this.di(a))?a.o:0});
g.nM.prototype.Qn=g.ca(1,function(){return 0});
g.QI.prototype.J=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var bxa=/^#(?:[0-9a-f]{3}){1,2}$/i,cxa=/#(.)(.)(.)/,Fxa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,k6={gw:0,NORMAL:1,jw:2},Rxa="default monoSerif propSerif monoSans propSans casual cursive smallCaps".split(" "),Pxa=["none","raised","depressed","uniform","dropShadow"],C6=/^#(?:[0-9a-f]{3}){1,2}$/i;var f7={Hv:0,E0:1,hF:2},gxa=["left","right","center"],h6={Zp:0,iq:1,B1:2,BW:3},B6={Z2:0,Bm:5,qq:6},i6={fq:0,bq:1,hq:2};var d7={windowColor:g.N2.Rp,jk:0,textAlign:f7.hF,Tg:7,ti:50,Oi:100,rb:{background:g.N2.Rp,Ue:.75,Yh:g.M2.NONE,color:g.N2.uq,fontFamily:g.O2.gq,gj:0,Ih:1,offset:k6.NORMAL}};g.p(d6,g.aS);g.p(e6,g.aS);var f6=0;g.p(j6,g.Y);g.h=j6.prototype;g.h.aN=function(a,b){var c=g.Dh(this.element,this.element.parentElement);this.ea=a-c.x;this.da=b-c.y;g.S(this.element,"ytp-dragging")};
g.h.ZM=function(a,b){var c=g.Gh(this.element),d=a-this.ea-.02*this.sa,e=b-this.da-.02*this.ra,f=(d+c.width/2)/this.V*3;f=Math.floor(g.Zc(f,0,2));var k=(e+c.height/2)/this.ga*3;k=Math.floor(g.Zc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.V;d=100*g.Zc(d,0,1);c=(e+k/2*c.height)/this.ga;c=100*g.Zc(c,0,1);this.F.params.Tg=l;this.F.params.Oi=c;this.F.params.ti=d;this.o.Tg=l;this.o.Oi=c;this.o.ti=d;this.FC()};
g.h.YM=function(){g.Sp(this.element,"ytp-dragging")};
g.h.FC=function(){this.Li(this.B)};
g.h.Yb=function(){return this.type};
g.h.Li=function(a){var b=Math.min(this.gy(),this.V),c=this.fy();g.nh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Gq(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.o.ti+2,e=this.o.Tg;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.A.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.o.Oi+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.A.offsetHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.nh(this.element,a)};
g.h.Gq=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.J||this.B.length>b)b=0,this.J=!1,this.B=[],this.D=[],this.G=[],this.C=null,g.Fd(this.A);for(;b<a.length;b++)hxa(this,a[b])};
g.h.gy=function(){return 0};
g.h.fy=function(){return 0};
g.h.toString=function(){return g.Y.prototype.toString.call(this)};ixa.prototype.B=function(){};n6.prototype.clear=function(){this.B=this.o=this.mode=0;this.g=[];this.reset()};
n6.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var jxa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];o6.prototype.set=function(a){this.g=a};
o6.prototype.get=function(){return this.g};
p6.prototype.clear=function(){this.g=0};
p6.prototype.update=function(){this.g=2==this.g?1:0};
p6.prototype.matches=function(a,b){return 0!=this.g&&a==this.A&&b==this.o};
q6.prototype.pn=function(a){this.qe=a.qe;this.timestamp=a.timestamp;this.g=a.g};
q6.prototype.reset=function(){this.timestamp=this.qe=0;this.g=!1};
r6.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0==d.qe?a+"_":a+String.fromCharCode(d.qe)}a+="\n"}return a};
r6.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.g=0;this.o=this.Hc=1};
var oxa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],pxa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],qxa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],rxa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];x6.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.o=this.D;this.A=this.F;this.g=this.o;var c=(a<<2)+(b<<1)+0;this.D.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
m6.prototype.reset=function(a){this.C=a;this.g.clear();this.B=this.A;this.A.reset(a,0);this.D.reset(a,1)};z6.prototype.reset=function(){};g.p(A6,z6);A6.prototype.g=function(a){var b=[];this.o||(this.o=g6(this.A),b.push(this.o));a=g.ma(a.firstChild.childNodes);for(var c=a.next();!c.done;c=a.next())xxa(c.value,this.o.id,b);return b};g.p(D6,z6);
D6.prototype.g=function(a){var b=[];this.o||(this.o=g6(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=g6());
var k={};f&&(g.Ha(k,f.params),f=f.params.rb)&&(k.rb={},g.Ha(k.rb,f));e.getAttribute("rc")&&(k.cp=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.TH=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Tg=0>f||8<f?7:f);e.getAttribute("ah")&&(k.ti=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.Oi=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.ck=h6.iq,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.ck=h6.Zp));e.getAttribute("bc")&&(k.rb||(k.rb={}),k.rb.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.rb||(k.rb={}),k.rb.Ue=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.rb||(k.rb={}),k.rb.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.aU=(0,window.parseInt)(e.getAttribute("sd"),10));
f=(0,window.parseInt)(e.getAttribute("d"),10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"0";c=new e6(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],xxa(a,this.o.id,d),d=g.ma(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.p(E6,z6);
E6.prototype.g=function(a){a.firstChild.getAttribute("format");a=g.ma(a.firstChild.childNodes);for(var b=a.next();!b.done;b=a.next())switch(b=b.value,b.tagName){case "head":var c=b;break;case "body":var d=b}if(c)for(c=g.ma(c.childNodes),a=c.next();!a.done;a=c.next())switch(a=a.value,a.tagName){case "pen":b=a.getAttribute("id");var e=this.o,f={},k=a.getAttribute("p");k&&g.Ha(f,this.o[k]);k=G6(a,"b");null!=k&&(f.bold=k);k=G6(a,"i");null!=k&&(f.Hs=k);k=G6(a,"u");null!=k&&(f.underline=k);k=H6(a,"et");
null!=k&&(f.Yh=k);k=H6(a,"of");null!=k&&(f.offset=k);k=I6(a,"bc");null!=k&&(f.background=k);k=I6(a,"ec");null!=k&&(f.Ww=k);k=I6(a,"fc");null!=k&&(f.color=k);k=H6(a,"fs");void 0!=k&&k!=g.O2.lm&&(f.fontFamily=k);k=F6(a,"sz");void 0!=k&&(f.gj=k/100-1);k=F6(a,"bo");void 0!=k&&(f.Ue=k/255);a=F6(a,"fo");void 0!=a&&(f.Ih=a/255);e[b]=f;break;case "ws":b=a.getAttribute("id");this.D[b]=yxa(this,a);break;case "wp":b=a.getAttribute("id"),this.C[b]=zxa(this,a)}c=[];if(d)for(a={},b=void 0,d=g.ma(d.childNodes),
e=d.next();!e.done;e=d.next())switch(e=e.value,e.tagName){case "w":var l=Axa(this,e,!1);(e=a[l.id])&&e.end>l.start&&(e.end=l.start);a[l.id]=l;c.push(l);break;case "p":var m=b,n=Pc;f=[];k=e.getAttribute("w")||this.A;var q=!!G6(e,"a"),r=F6(e,"t")||0,w=F6(e,"d")||5E3;!n&&!q&&m&&m.windowId==k&&m.end>r&&(m.end=r);m=q?B6.qq:B6.Bm;n=this.o[e.getAttribute("p")];for(var z=e.childNodes,B=0;B<z.length;B++){var C=z[B];0<B&&(q=!0);if("s"==C.tagName){var N=C;C=r;var da=w,Ea=k,Ba=q,Ca=m,Le=N.textContent?N.textContent:
"",Za=this.o[N.getAttribute("p")];N=F6(N,"t")||0;C=new d6(C+N,da-N,Ca,Ea,Le,Ba,Za)}else C=new d6(r,w,m,k,C.textContent||"",q,n);f.push(C)}b&&"\n"==b.text&&(b.text="");if(0<f.length){b=f[f.length-1];var Pc=null!=e.getAttribute("d");f[0].windowId==this.A&&(l=Axa(this,e,!0),c.push(l));e=g.ma(f);for(f=e.next();!f.done;f=e.next())f=f.value,f.windowId=l.id,l.o.push(f),c.push(f)}}return c};g.p(J6,ixa);J6.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+f6++;c=c/1E3-this.F;d=d/1E3-this.F;var k=B6.Bm;a=new e6(c,d-c,k,f,{textAlign:f7.Hv,Tg:0,ti:2.5*b,Oi:5.33*a});e=new d6(c,d-c,k,f,e);this.A.push(a);this.A.push(e)}};
g.p(L6,z6);L6.prototype.g=function(a){a=new J6(a,0,this.B);if(Cxa(a)){for(;a.g<a.o.byteLength;)for(0==a.version&&(a.D=Bxa(a)*(1E3/45)),a.C=K6(a);0<a.C;a.C--){var b=K6(a),c=K6(a),d=K6(a);b&4&&(b&3)==this.o&&(0==this.o||1==this.o)&&(b=this.A,b.g.push({time:a.D,type:this.o,Rw:c,Sw:d,order:b.g.length}))}nxa(this.A,a);return a.A}return[]};
L6.prototype.reset=function(){this.A.clear()};g.p(O6,z6);
O6.prototype.g=function(a,b){for(var c=[],d=a.split(Uxa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Vxa.test(f)){var l=g7.exec(f);if(l&&3<=l.length){var m=P6(l[1]);l=P6(l[2])-m;m+=k;f=f.substring(g7.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");g7.lastIndex=0;var n=f;f={};this.o||(this.o=g6({Vs:i6.fq}),c.push(this.o));var q=this.o;k=B6.Bm;if(0>n.indexOf("<")&&0>n.indexOf("&"))c.push(new d6(m,l,k,q.id,n,!1,g.Zb(f)?void 0:f));else{n=n.split(Wxa);1!=n.length&&(k=B6.qq,q="_"+Xxa++,q=new e6(m,l,k,
q,{}),c.push(q));for(var r=m,w=0;w<n.length;w++){var z=n[w];if(0==w%2){var B=g.vr("<html>"+z+"</html>");if(B.getElementsByTagName("parsererror").length){var C=B.createElement("span");C.appendChild(B.createTextNode(z))}else C=B.firstChild;Exa(this,r,l-(r-m),k,q,0<w,C,f,c)}else r=P6(z)}}}g7.lastIndex=0}}return c};
var Xxa=0,Vxa=/^NOTE/,Uxa=/(?:\r\n|\r|\n){2,}/,g7=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3}).*(?:\r\n|\r|\n)","gm"),Wxa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.p(Q6,g.K);Q6.prototype.Hd=function(){this.g=null};
Q6.prototype.W=function(){g.K.prototype.W.call(this);this.Hd()};
Q6.prototype.rC=function(){return!1};g.p(R6,Q6);g.h=R6.prototype;g.h.Ps=function(a,b){var c=this.Pk(a),d=(0,g.A)(function(c){this.A=null;b(c.responseText,a)},this);
this.Hd();this.A=g.hF(c,{format:"RAW",Vb:d,withCredentials:!0})};
g.h.Qs=function(a,b,c,d){this.B=c;if(d)for(b=g.ma(d.captionTracks),c=b.next();!c.done;c=b.next())N6(this.o,c.value);a()};
g.h.Pk=function(a){var b=a.I,c={};if(this.B||a.A)c.fmt=this.B||"srv"+a.A;a.g&&(c.tlang=a.g.languageCode);return g.dF(b,c)};
g.h.Hd=function(){Q6.prototype.Hd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Hd();Q6.prototype.W.call(this)};S6.prototype.contains=function(a){a=g.Bb(this.qb,a);return 0<=a||0>a&&1==(-a-1)%2};
S6.prototype.length=function(){return this.qb.length/2};g.p(T6,g.K);g.h=T6.prototype;g.h.W=function(){g.K.prototype.W.call(this);this.o&&this.o.abort()};
g.h.zA=function(a){var b=this.g;this.g=g.db(this.L.fh(a).g);b!=this.g&&this.I&&this.I()};
g.h.reset=function(){this.B=new S6;this.o&&(this.o.abort(),this.o=null)};
g.h.Cz=function(){var a;if(a=null!==this.g)a=this.g,a=a.ma.Bi(a);if(a&&!this.o&&!(this.g&&30<this.g.startTime-this.J.getCurrentTime())){a=this.g;a=a.ma.vl(a);if(!this.B.contains(a.g[0].va)){var b=g.SL(g.ZL(a,{})),c={format:"RAW",Fd:(0,g.A)(this.CR,this),withCredentials:!0};this.C&&(c.responseType="arraybuffer");this.o=g.hF(b,c);this.A=a;b=this.B;c=this.A.g[0].va;var d=g.Bb(b.qb,c);0<=d||0>d&&1==(-d-1)%2||(d=-d-1,0<d&&1==c-b.qb[d-1]&&d<b.qb.length&&1==b.qb[d]-c?(g.qb(b.qb,d),g.qb(b.qb,d-1)):0<d&&1==
c-b.qb[d-1]?b.qb[d-1]=c:d<b.qb.length&&1==b.qb[d]-c?b.qb[d]=c:(g.xb(b.qb,d,0,c),g.xb(b.qb,d+1,0,c)))}this.g=g.db(a.g)}this.F.start()};
g.h.CR=function(a){(this.C?!a.response:!a.responseText)||400<=a.status||null===this.D||(this.C?this.D(a.response,1E3*this.A.g[0].startTime):this.D(a.responseText,1E3*this.A.g[0].startTime));this.o=this.A=null};g.p(U6,Q6);g.h=U6.prototype;g.h.Ps=function(a,b){this.Hd();var c=this.D.g[a.o];if(c){var d=1E3*c.index.Qn(c.index.xg()),e=g.X(this.T).zf;this.A=new T6(new g.tL,this.T,c,function(c,e){b(c,a,e,d)},e,(0,g.A)(function(){e&&(this.A&&this.A.reset(),this.g&&this.g.reset(),this.B=!0)},this))}};
g.h.rC=function(){var a=this.B;this.B=!1;return a};
g.h.Qs=function(a){g.X(this.T).zf?(N6(this.o,new g.QI({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),N6(this.o,new g.QI({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}))):N6(this.o,new g.QI({format:1,languageCode:"en",languageName:"English",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));a()};
g.h.Hd=function(){Q6.prototype.Hd.call(this);this.A&&(this.A.dispose(),this.A=null)};
g.h.Pk=function(){return""};
g.h.W=function(){this.Hd();Q6.prototype.W.call(this)};g.p(V6,j6);V6.prototype.Gq=function(a){var b=this.F.o;j6.prototype.Gq.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Ha(d,c.o);g.Ha(d,Yxa);var e=c.o;var f=d}hxa(this,c,d)}};
var Yxa={Sr:!0};g.p(W6,j6);g.h=W6.prototype;g.h.FC=function(){g.Ft(this.Y)};
g.h.GR=function(){g.Sp(this.element,"ytp-rollup-mode");this.Li(this.na,!0)};
g.h.gy=function(){return this.I};
g.h.fy=function(){return this.F.params.cp*X6(this)};
g.h.Li=function(a,b){this.na=a;if(X6(this)){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.I;this.I=0;j6.prototype.Li.call(this,a);this.I=Math.max(c,this.A.offsetWidth+1);c=this.F.params.cp*X6(this)-this.A.offsetHeight;c!=this.O&&(b||(0,window.isNaN)(this.O)||(g.S(this.element,"ytp-rollup-mode"),this.Y.gc()),g.nh(this.A,"transform",c?"translateY("+c+"px)":""),this.O=c);j6.prototype.Li.call(this,a)}else j6.prototype.Li.call(this,
a)};g.p(Y6,Q6);g.h=Y6.prototype;g.h.Ps=function(a,b){var c=this.Pk(a),d=(0,g.A)(function(c){this.A=null;b(c.responseText,a)},this);
this.Hd();this.A=g.hF(c,{format:"RAW",Vb:d,withCredentials:!0})};
g.h.Qs=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.B,fmts:Number(b||!1),vssids:1};this.lz&&(b.asrs=1);d=g.dF(d,b);b=(0,g.A)(function(b){this.A=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.o,e=g.ma(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),q=m.getAttribute("lang_translated"),r=m.getAttribute("name"),w=m.getAttribute("kind"),z=m.getAttribute("id"),B="true"==m.getAttribute("cantran");
m=m.getAttribute("vss_id");N6(d,new g.QI({formats:l,format:c,languageCode:n,languageName:q,name:r,kind:w,id:z,is_servable:!0,is_translateable:B,vss_id:m}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),q=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),l={languageCode:l,languageName:n,languageOriginal:q,id:r},this.F[l.languageCode]=l.languageName,this.C.push(new g.PI(l))}a()},this);
this.Hd();this.A=g.hF(d,{format:"RAW",Vb:b,withCredentials:!0})};
g.h.Pk=function(a){var b=this.D,c={v:this.B,type:"track",lang:a.o,name:a.C,kind:a.B,fmt:a.A};a.g&&(c.tlang=a6(a));return b=g.dF(b,c)};
g.h.Hd=function(){Q6.prototype.Hd.call(this);this.A&&this.A.abort()};
g.h.W=function(){this.Hd();Q6.prototype.W.call(this)};g.p(b7,g.aX);g.h=b7.prototype;g.h.W=function(){Z6(this)||Mxa(this,!1);g.aX.prototype.W.call(this)};
g.h.rA=function(){return Z6(this)?!this.o.Ba:this.o.captionTracks.length&&this.g.uh().Ik?!0:Ixa(this)};
g.h.load=function(a){g.aX.prototype.load.call(this);this.D=this.g.uh();if(this.B||a)this.A?(a?this.aC(a,this.A):3!=this.g.Ya()&&this.B.Ps(this.A,(0,g.A)(this.aC,this)),this.g.za("captionschanged",b6(this.A))):this.g.za("onCaptionsTrackListChanged");else{var b;a=this.o;a.Ba||g.X(this.T).zf&&null!=a.ua&&null!=a.ua.g.rawcc?b=new U6(this.o.ua,this.g):this.o.captionTracks.length?b=new R6(this.o):b=new Y6(this.o.bn,this.o.videoId,this.o.Wg||this.F.Wg||g.sQ(this.o,"yt:cc_default_lang")||this.F.Sa,this.o.an);
this.B=b;b.Qs((0,g.A)(this.iS,this),!0,Z6(this)?"vtt":void 0,this.g.uh())}};
g.h.unload=function(){if(Z6(this))for(var a=g.nd(window.document,"track",void 0,this.T.app.D.g),b=0;b<a.length;b++)g.Id(a[b]);else this.da&&g.Gt(this.da),g.uW(this.g,"captions"),this.J=[],this.B&&this.B.Hd(),this.I&&g.rW(this.g,this.I),this.Gu();g.aX.prototype.unload.call(this);(a=g.dW(this.g.app))&&a.D&&g.GQ(a.D.A);this.g.za("captionschanged",{})};
g.h.iS=function(){if(this.O||Ixa(this))var a=Jxa(this,this.O);if(Z6(this))for(var b=M6(this.B.o,!0),c=0;c<b.length;c++){var d=b[c],e={kind:"subtitles",label:g.RI(d),srclang:a6(d),src:this.B.Pk(d)};d==a&&(e["default"]=1);d=this.T.app.D;e=[g.zd("TRACK",e)];for(var f=0;f<e.length;f++)d.g.appendChild(e[f])}else!this.A&&a&&c7(this,a),this.g.za("onCaptionsTrackListChanged"),this.g.za("onApiChange")};
g.h.gU=function(){this.loaded&&!Z6(this)&&this.unload()};
g.h.aC=function(a,b,c,d){if(a){this.B.rC()&&(this.J=[],g.uW(this.T,"captions"),this.aa.Sk());a=Hxa(this.B,a,b,c,d);c={trackName:b.C,trackKind:b.B,trackLangCode:a6(b)};b.g&&(c.fromLangCode=b.o);g.lW(this.g,"cc",c);if(this.A!=(this.D&&this.D.Ik)){if(this.O&&!g.$N(this.F)&&!g.aO(this.F)){g.Gt(this.da);b=g6({Tg:0,ti:5,Oi:5,cp:2,textAlign:f7.Hv,ck:h6.Zp,lang:"ja"});this.N=[b];c=g.U("YTP_CLICK_FOR_SETTINGS").split("$GEAR_ICON");this.ga||(d=new g.GW(g.GE()),g.L(this,d),this.ga=d.element);d=b.end-b.start;
var e=g.RI(this.A);e&&this.N.push(new d6(b.start,d,0,b.id,e));this.N.push(new d6(b.start,d,0,b.id,c[0]),new d6(b.start,d,0,b.id,this.ga,!0),new d6(b.start,d,0,b.id,c[1],!0));g.rW(this.g,this.N);this.da.gc()}if(this.O||g.$N(this.F))e7(this,"module-enabled",!0),this.D&&(this.D.g=this.A);(b=g.dW(this.g.app))&&b.D&&g.GQ(b.D.A)}g.rW(this.g,a);this.O=!1}};
g.h.GM=function(a){this.J.push(a);this.aa.Sk()};
g.h.HM=function(a){g.rb(this.J,a);this.aa.Sk()};
g.h.bT=function(a){if(a instanceof e6){var b=this.L[a.id];b&&b.F!=a&&(b.dispose(),delete this.L[a.id],b=null);b||(b=Kxa(this,a))&&(this.L[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.qT=function(){Lxa(this,this.N);this.N=null};
g.h.DD=function(){this.aa.stop();exa(this.V);this.J.sort(g.cS);var a=this.J;if(this.I){var b=(0,g.Kd)(a,function(a){return-1==this.I.indexOf(a)},this);
b.length&&(a=b)}(0,g.H)(a,this.bT,this);g.Nb(this.L,function(a,b){this.V[b]?(a.element.parentNode||g.yW(this.g,a.element,4),a.Li(this.V[b])):(a.dispose(),delete this.L[b])},this)};
g.h.EC=function(){$6(this,{},!0)};
g.h.zr=function(){var a=d7.rb;a={background:a.background,backgroundOpacity:a.Ue,charEdgeStyle:a.Yh,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.gj,textOpacity:a.Ih,windowColor:d7.windowColor,windowOpacity:d7.jk};var b=a7(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Ju=function(a,b){var c={};g.Ha(c,a7(this,"display-settings"));g.Ha(c,a);$6(this,c,b);this.g.X("captionssettingschanged")};
g.h.Gu=function(){!Z6(this)&&this.loaded&&(g.Nb(this.L,function(a,b){a.dispose();delete this.L[b]},this),this.DD())};
g.h.vt=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Zc(b,-2,4);this.Ju({fontSizeIncrement:c});return c;case "reload":b&&!Z6(this)&&c7(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.F.Hb&&e7(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(Z6(this))break;if(!g.Aa(b))break;if(g.Zb(b)){c7(this,null,!0);break}for(var d=M6(this.B.o,!0),e=0;e<d.length;e++){var f=d[e];f.o!=b.languageCode||c&&f.D!=b.languageName||(c=b.translationLanguage?
axa(f,b.translationLanguage):f)}!c||c==this.A&&this.loaded||c7(this,c,!0)}else return this.loaded&&this.A&&this.A!=(this.D&&this.D.Ik)?b6(this.A):{};return"";case "tracklist":return this.B?(0,g.J)(M6(this.B.o,b&&b.includeAsr),function(a){return b6(a)}):[];
case "translationLanguages":return this.B?this.B.C:[];case "displaySettings":c=this.zr();if(g.$N(this.F)&&b&&g.Aa(b))if(b.reset)this.EC();else{f={};for(d in b)switch(d){case "color":case "background":case "windowColor":f[d]=Nxa(b[d],c[d]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[d]=Oxa(b[d],c[d]);break;case "charEdgeStyle":f[d]=Qxa(b[d],c[d]);break;case "fontSizeIncrement":f[d]=Txa(b[d],c[d]);break;case "fontFamilyOption":f.fontFamily=Sxa(b[d],c[d])}for(e in f)f[e+
"Override"]=!0;this.Ju(f,!0);c=this.zr()}c.fontFamilyOption=Rxa[c.fontFamily];c.charEdgeStyle=Pxa[c.charEdgeStyle];return c;case "sampleSubtitles":Z6(this)||void 0==b||Mxa(this,!!b);break;case "xmlTrack":b&&this.F.Hb&&(Z6(this)||c7(this,new g.QI({languageName:b.name}),!1,b.xml))}};
g.h.EM=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.F.Hb&&a.push("stickyLoading","xmlTrack");return a};
g.h.FM=function(){var a=this.A;return a?{cc:a.F}:{}};
g.h.sD=function(){this.loaded&&this.A?(e7(this,"module-enabled",!1),this.unload()):c7(this,this.A||Jxa(this,!0),!0)};
g.h.UO=function(){this.o.captionTracks.length&&(this.loaded&&this.unload(),this.rA()&&this.load())};g.mX("captions",b7);})(_yt_player);
