(function(g){var window=this;var Zxa=function(a,b,c,d){var e=b.dc();g.T(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.bc(c,d?d:"mqdefault.jpg");var k=b instanceof g.dQ?g.gX(b.lengthSeconds):null,l=!!f;f=l&&"RD"==g.eS(f).type;var m=b instanceof g.dQ?b.Ba:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,watch:g.U("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Un(c),is_live:m,is_list:l,is_mix:f,background:d?"background-image: url("+
d+")":""};b instanceof g.gS&&(c.playlist_length=b.getLength());a.update(c)},h7=function(a,b){g.fX.call(this,{H:"div",
ca:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.o=a;this.N=!1},i7=function(a){var b={H:"span",
M:"ytp-upnext-top",K:[{H:"span",M:"ytp-upnext-header",K:[g.U("YTP_PLAYLIST_UP_NEXT")]},{H:"span",M:"ytp-upnext-title",K:["{{title}}"]},{H:"span",M:"ytp-upnext-author",K:["{{author}}"]}]},c={href:"{{url}}","aria-label":g.U("YTP_AUTOPLAY_NEXT")};b={H:"div",M:"ytp-upnext",R:{"aria-label":"{{watch}}"},K:[{H:"div",M:"ytp-cued-thumbnail-overlay-image",R:{style:"{{background}}"}},b,{H:"a",M:"ytp-upnext-autoplay-icon",R:c,K:[{H:"svg",R:{height:"100%",version:"1.1",viewBox:"0 0 98 98",width:"100%"},K:[{H:"circle",
M:"ytp-svg-autoplay-circle",R:{cx:"49",cy:"49",fill:"#000","fill-opacity":"0.8",r:"48"}},{H:"circle",M:"ytp-svg-autoplay-ring",R:{cx:"-49",cy:"49","fill-opacity":"0",r:"46.5",stroke:"#FFFFFF","stroke-dasharray":"293","stroke-dashoffset":"-293","stroke-width":"4",transform:"rotate(-90)"}},{H:"polygon",M:"ytp-svg-autoplay-triangle",R:{fill:"#fff",points:"32,27 72,49 32,71"}}]}]},{H:"span",M:"ytp-upnext-bottom",K:[{H:"span",M:"ytp-upnext-cancel"},{H:"span",M:"ytp-upnext-paused",K:[g.U("YTP_AUTOPLAY_PAUSED_3")]}]},
{H:"span",M:"ytp-upnext-close"}]};g.Y.call(this,b);this.B=null;c=this.wa["ytp-upnext-cancel"];b=this.wa["ytp-upnext-close"];this.B=new g.Y({H:"button",ca:["ytp-upnext-cancel-button","ytp-button"],R:{tabindex:0,"aria-label":g.U("YTP_AUTOPLAY_CANCEL")},K:[g.U("YTP_CANCEL")]});g.L(this,this.B);this.B.U("click",this.vB,this);this.B.Ga(c);c=new g.Y({H:"button",ca:["ytp-upnext-close-button","ytp-button"],R:{"aria-label":g.U("YTP_AUTOPLAY_CANCEL")}});g.L(this,c);c.U("click",this.vB,this);c.Ga(b);this.o=
a;this.J=this.wa["ytp-svg-autoplay-ring"];this.F=this.D=this.A=this.C=null;this.G=new g.Et(this.kn,5E3,this);g.L(this,this.G);this.I=0;this.P(this.wa["ytp-upnext-autoplay-icon"],"click",this.dR);this.sB();this.P(a,"autonavvisibility",this.sB);this.P(a,"mdxnowautoplaying",this.sQ);this.P(a,"mdxautoplaycanceled",this.tQ);this.P(a,"mdxautoplayupnext",this.GD);3==this.o.Ya()&&(a=(a=g.cW(g.YV(this.o)))?a.yI():null)&&this.GD(a)},$xa=function(a,b){a.C=b;
Zxa(a,b,g.X(a.o),"hqdefault.jpg")},j7=function(a,b){a.A||(g.HG("a11y-announce",g.U("YTP_PLAYLIST_UP_NEXT")+" "+a.C.title),a.I=(0,g.UG)(),a.A=new g.Et((0,g.A)(a.Eq,a,b),25),a.Eq(b));
g.Sp(a.element,"ytp-upnext-autoplay-paused")},l7=function(a){k7(a);
a.I=(0,g.UG)();a.Eq();g.S(a.element,"ytp-upnext-autoplay-paused")},k7=function(a){a.A&&(a.A.dispose(),a.A=null)},aya=function(a){h7.call(this,a,"subscribecard-endscreen");
var b=a.fa();this.A=new g.Y({H:"div",M:"ytp-subscribe-card",K:[{H:"img",M:"ytp-author-image",R:{src:b.profilePicture}},{H:"div",M:"ytp-subscribe-card-right",K:[{H:"div",M:"ytp-author-name",K:[b.author]},{H:"div",M:"html5-subscribe-button-container"}]}]});g.L(this,this.A);this.A.Ga(this.element);this.B=new g.f1(g.U("YTP_SUBSCRIBE"),null,g.U("YTP_UNSUBSCRIBE"),null,!0,!1,b.Wl,b.subscribed,"trailer-endscreen",null,null,a);g.L(this,this.B);this.B.Ga(this.A.wa["html5-subscribe-button-container"]);this.hide()},
m7=function(a){var b=g.X(a);
b=b.A&&!b.F;g.Y.call(this,{H:"a",M:"ytp-videowall-still",R:{href:"{{url}}",target:b?"_blank":"","aria-label":"{{watch}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{H:"div",M:"ytp-videowall-still-image",R:{style:"{{background}}"}},{H:"span",M:"ytp-videowall-still-info",K:[{H:"span",M:"ytp-videowall-still-info-bg",K:[{H:"span",M:"ytp-videowall-still-info-content",R:g.oF||g.df?{style:"will-change: opacity"}:void 0,K:[{H:"span",M:"ytp-videowall-still-info-title",
K:["{{title}}"]},{H:"span",M:"ytp-videowall-still-info-author",K:["{{author_and_views}}"]},{H:"span",M:"ytp-videowall-still-info-live",K:[g.U("YTP_LIVE")]},{H:"span",M:"ytp-videowall-still-info-duration",K:["{{duration}}"]}]}]}]},{H:"span",ca:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-icon"},g.U("YTP_PLAYLIST"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (",{H:"span",K:["{{playlist_length}}"]},")"]}]},{H:"span",
ca:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{H:"span",M:"ytp-videowall-still-listlabel-mix-icon"},g.U("YTP_MIX"),{H:"span",M:"ytp-videowall-still-listlabel-length",K:[" (50+)"]}]}]});this.B=b;this.o=a;this.A=null;this.U("click",this.C);this.U("keypress",this.D);if(g.X(a).ea){a=a.app.aa;b=this.element;g.kb(a.g,b);g.pb(a.g,b);var c=String(a.G++);b.setAttribute("data-visual-id",c);g.Ze(this,(0,g.A)(a.F,a,b))}},n7=function(a){h7.call(this,a,"videowall-endscreen");
this.aa=a;this.G=0;this.B=[];this.I=this.D=this.C=null;this.J=this.V=!1;this.F=new g.pG(this);g.L(this,this.F);this.L=new g.Et(g.Ga(g.S,this.element,"ytp-show-tiles"),0);g.L(this,this.L);var b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-previous"],R:{"aria-label":g.U("YTP_PREVIOUS")},K:[g.rE()]});g.L(this,b);b.Ga(this.element);b.U("click",this.QM,this);this.O=new g.GW({H:"div",M:"ytp-endscreen-content"});g.L(this,this.O);this.O.Ga(this.element);b=new g.Y({H:"button",ca:["ytp-button","ytp-endscreen-next"],
R:{"aria-label":g.U("YTP_NEXT")},K:[g.sE()]});g.L(this,b);b.Ga(this.element);b.U("click",this.PM,this);this.A=new i7(a);g.L(this,this.A);g.yW(this.o,this.A.element,4);this.hide()},o7=function(a){return g.zW(a.o)&&a.Iq()&&!a.I},bya=function(a){return(0,g.J)(a.jg,function(a){return g.h_(a)})},cya=function(a,b,c){return 0==b&&a.C.length&&2<=c/2&&2<=c/2&&g.X(a.o).experiments.g("video_wall_emphasize_first")?4:2},p7=function(a){var b=a.wt();
b!=a.V&&(a.V=b,a.o.X("autonavvisibility"))},q7=function(a){g.aX.call(this,a);
g.mE({});this.o=null;this.isAvailable=!0;this.A=new g.pG(this);g.L(this,this.A);this.B=g.X(a);dya(a)?this.o=new n7(this.g):this.B.sa?this.o=new aya(this.g):this.o=new h7(this.g);g.L(this,this.o);g.yW(this.g,this.o.element,4);this.DC();this.A.P(a,"videodatachange",this.DC,this);this.A.P(a,"crn_endscreen",this.rM,this);this.A.P(a,"crx_endscreen",this.sM,this)},dya=function(a){a=g.X(a);
return a.Id&&!a.sa};g.p(h7,g.fX);h7.prototype.create=function(){this.N=!0};
h7.prototype.destroy=function(){this.N=!1};
h7.prototype.Iq=function(){return!1};
h7.prototype.wt=function(){return!1};g.p(i7,g.Y);g.h=i7.prototype;g.h.kn=function(){this.D&&(this.G.stop(),this.Ca(this.F),this.F=null,this.D.close(),this.D=null)};
g.h.sB=function(){g.MW(this,g.ZV(this.o))};
g.h.TQ=function(){window.focus();this.kn()};
g.h.hide=function(){g.Y.prototype.hide.call(this)};
g.h.Eq=function(a){a=a||g.X(this.o).experiments.o("autoplay_time")||1E4;var b=Math.min((0,g.UG)()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-293*(a+1));1<=a&&3!=this.o.Ya()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;var b=g.X(this.o);if(b.experiments.g("autonav_notifications")&&a&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;g.lW(this.o,"xwebnotifications",{permission:c});"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=this.C.dc(),this.kn(),this.D=new window.Notification(g.U("YTP_PLAYLIST_UP_NEXT"),{body:c.title,icon:c.bc(b)}),this.F=this.P(this.D,"click",this.TQ),this.G.start())}k7(this);
this.o.Fj(!1,a)};
g.h.dR=function(a){!g.Qd(this.B.element,g.fG(a))&&g.WZ(a,this.o)&&this.select()};
g.h.vB=function(){g.mW(this.o,"autonavcancel");g.aW(this.o,!0)};
g.h.sQ=function(a){this.o.Ya();this.show();j7(this,a)};
g.h.GD=function(a){this.o.Ya();this.C&&this.C.dc().videoId==a.dc().videoId||$xa(this,a)};
g.h.tQ=function(){this.o.Ya();k7(this);this.hide()};
g.h.W=function(){k7(this);this.kn();g.Y.prototype.W.call(this)};g.p(aya,h7);g.p(m7,g.Y);m7.prototype.Vj=function(){var a=this.A.dc().videoId,b=this.A.getPlaylistId();g.R1(this.o.app,a,this.A.Vd,b,void 0,void 0)};
m7.prototype.C=function(a){g.CW(this.o,this.element);g.WZ(a,this.o,this.B,this.A.Vd||void 0)&&this.Vj()};
m7.prototype.D=function(a){switch(a.keyCode){case 13:case 32:g.kG(a)||(this.Vj(),g.mG(a))}};g.p(n7,h7);g.h=n7.prototype;g.h.create=function(){h7.prototype.create.call(this);var a=this.o.fa();a&&(this.C=bya(a),this.D=a);this.yh();this.F.P(this.o,"appresize",this.yh);this.F.P(this.o,"videodatachange",this.RM);this.F.P(this.o,"autonavchange",this.uA);this.F.P(this.o,"autonavcancel",this.OM);this.F.P(this.element,"transitionend",this.jS)};
g.h.destroy=function(){g.rG(this.F);g.af(this.B);this.B=[];this.C=null;h7.prototype.destroy.call(this);g.Sp(this.element,"ytp-show-tiles");this.L.stop()};
g.h.Iq=function(){return 1!=this.D.autonavState};
g.h.show=function(){h7.prototype.show.call(this);g.Sp(this.element,"ytp-show-tiles");g.X(this.o).isMobile?g.Ft(this.L):this.L.start();(this.J||this.I&&this.I!=this.D.clientPlaybackNonce)&&g.aW(this.o,!1);var a=o7(this);g.zW(this.o)&&g.X(this.o).experiments.g("ui_logging")&&g.lW(this.o,"end",{cancelButtonShow:a?"1":"0",state:this.Iq()?"enabled":"disabled"});a?(p7(this),2==this.D.autonavState?g.X(this.o).experiments.g("fast_autonav_in_background")&&3==this.o.wh()?this.A.select(!0):j7(this.A):3==this.D.autonavState&&
l7(this.A)):(g.aW(this.o,!0),p7(this))};
g.h.hide=function(){h7.prototype.hide.call(this);l7(this.A);p7(this)};
g.h.jS=function(a){g.fG(a)==this.element&&this.yh()};
g.h.yh=function(){if(this.C&&this.C.length){g.S(this.element,"ytp-endscreen-paginate");var a=g.Gh(this.element),b=a.width/a.height,c=96/54,d=2,e=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.C.length,m=Math.pow(2,2),n=l*m,q=cya(this,0,k),r=cya(this,1,k);n+=Math.pow(q,2)-m;n+=Math.pow(r,2)-m;for(n-=m;0<n&&(d<f||e<k);){var w=d/2,z=e/2,B=d<=f-2&&n>=z*m,C=e<=k-2&&n>=w*m;if((w+1)/z*c/b>b/(w/(z+1)*c)&&C)n-=w*m,e+=2;else if(B)n-=z*m,d+=2;else if(C)n-=w*m,e+=2;else break}c=!1;f=2+q;n>=3*m&&
6>=l*m-n&&(e>=f||d>=f)&&2>=r&&(c=!0);m=96*d;n=54*e;b=m/n<b?a.height/n:a.width/m;b=Math.min(b,2);m*=b;n*=b;m*=g.Zc(a.width/m||1,1,1.21);n*=g.Zc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Fh(a,m,n);g.nh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});$xa(this.A,this.C[0]);g.T(this.element,"ytp-endscreen-takeover",o7(this));p7(this);m+=4;n+=4;b=0;f=!1;for(k=0;k<d;k++)for(w=0;w<e;w++)if(z=2<r&&1<=b&&!f?b+1:b,B=0,c&&k>=d-2&&w>=e-2?B=1:0==
w%2&&0==k%2&&(w<q&&k<q?0==w&&0==k&&(B=q):2<r&&w>=e-r&&k>=d-r?w==e-r&&k==d-r&&(f=!0,z=1,B=r):B=2),z=g.$c(z+this.G,l),0!=B){C=this.B[b];C||(C=new m7(this.o),this.B[b]=C,a.appendChild(C.element));var N=Math.floor(n*w/e),da=Math.floor(m*k/d),Ea=Math.floor(n*(w+B)/e)-N-4,Ba=Math.floor(m*(k+B)/d)-da-4;g.uh(C.element,da,N);g.Fh(C.element,Ba,Ea);g.nh(C.element,"transitionDelay",(w+k)/20+"s");g.T(C.element,"ytp-videowall-still-mini",1==B);g.T(C.element,"ytp-videowall-still-large",2<B);B=C;z=this.C[z];B.A=
z;Zxa(B,z,g.X(B.o),g.Qp(B.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg");C=z.Vd;z=B.o;g.X(z).ea&&(z=z.app.aa,B=B.element,C=C&&C.itct,N=B.getAttribute("data-visual-id"),g.kb(z.g,B),g.AW(z,"onLogServerVeCreated",{id:N,tracking_params:C}));b++}g.T(this.element,"ytp-endscreen-paginate",b<l);for(d=this.B.length-1;d>=b;d--)e=this.B[d],g.Id(e.element),g.$e(e);this.B.length=b}};
g.h.RM=function(){var a=this.o.fa();this.D!=a&&(this.G=0,this.C=bya(a),this.D=a,this.yh())};
g.h.PM=function(){this.G+=this.B.length;this.yh()};
g.h.QM=function(){this.G-=this.B.length;this.yh()};
g.h.HK=function(){return!!this.A.A};
g.h.uA=function(a){1==a?(this.J=!1,this.I=this.D.clientPlaybackNonce,k7(this.A),this.g&&this.yh()):(this.J=!0,this.g&&o7(this)&&(2==a?j7(this.A):3==a&&l7(this.A)))};
g.h.OM=function(a){if(a){for(a=0;a<this.B.length;a++)g.DW(this.aa,this.B[a].element,!0);this.uA(1)}else this.I=null,this.J=!1;this.yh()};
g.h.wt=function(){return this.g&&o7(this)};g.p(q7,g.aX);g.h=q7.prototype;g.h.qA=function(){var a=this.g.fa(),b=!dya(this.g)||!(!a.jg||!a.jg.length);a=g.xQ(a,"ypc_module");var c=g.S1(this.g.app);return(b||!1)&&!a&&!c};
g.h.pA=function(){return this.o.wt()};
g.h.EK=function(){return this.pA()?this.o.HK():!1};
g.h.W=function(){g.uW(this.g,"endscreen");g.aX.prototype.W.call(this)};
g.h.load=function(){g.aX.prototype.load.call(this);this.o.show();g.X(this.g).sa&&.01>Math.random()&&g.lW(this.g,"end",{trailerEndscreenShow:1})};
g.h.unload=function(){g.aX.prototype.unload.call(this);this.o.hide();this.o.destroy();this.isAvailable=!1};
g.h.rM=function(a){this.qA()&&(this.o.N||this.o.create(),"load"==a.getId()&&this.load())};
g.h.sM=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.DC=function(){g.uW(this.g,"endscreen");var a=Math.max(1E3*(this.g.fa().lengthSeconds-10),0);a=new g.aS(a,0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.aS(0x8000000000000,0x8000000000000,{id:"load",priority:g.ZR.EF,namespace:"endscreen"});g.rW(this.g,[a,b])};g.mX("endscreen",q7);})(_yt_player);
